### ISSUE TITLE
slice indices must be integers

### ISSUE THREAD

**Issue by jackytu256** [AITTSMD/MTCNN-Tensorflow#20]
Hi,

I was trying to generate Pnet training data as the step 3. I have already checked that I putted WIDER_train folder in prepare_data dir, but the training data cannot be generated because of this error `(slice indices must be integers or None or have an __index__ method)`

**Comment by AITTSMD** [comment]
@jackytu256 hi,please check the input dimension.

**Comment by ltrottier** [comment]
I get this error also. The problem is that `nx1, ny1, nx2, ny2` are all float. This is because there is no float -> int cast at [line 117](https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_12net_data.py#L117) and [line 119](https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_12net_data.py#L119), as it is done at [line 92](https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_12net_data.py#L92).

@AITTSMD , you should fix that bug by adding `int(max(...))`.

**Comment by AITTSMD** [comment]
@ltrottier fix,thank u~
